### ISSUE TITLE
Do a comparison between execution clients based on Bedrock specifications

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#221]
Do a comparison between Nethermind and Erigon based on Bedrock specifications

Requirements:
- https://github.com/ethereum-optimism/optimism/blob/develop/specs/exec-engine.md
- https://github.com/ethereum-optimism/reference-optimistic-geth

**Comment by InoMurko** [comment]
_wip_
I've been reading the docs and from what I can tell, the important features of the client that need to be supported is ETH2 ready, because of the support of API calls:
```
engine_forkchoiceUpdatedV1
engine_newpayloadv1
engine_getpayloadv1
```

**Looking at Besu, Nethermind and Erigon - they're all ETH2 ready.**

Next, _P2P networking is strictly optional_
```
DiscV5
eth/66
```
The last protocol implementation is eth/67 (https://eips.ethereum.org/EIPS/eip-4938#backwards-compatibility) but all still (only go-eth at the time of writting supports eth/67, erigon follows) support eth/66. And the changes are added so that they're backwards compatible.

**Comment by wsdt** [comment]
Some things: 

Nethermind:
* .NET Core (at least enables us to run the client in Docker containers as well as on Non-Windows OS (with .NET Framework, we would have needed specific versions, Docker EE, etc.), went through that pain a few years ago. 

* C# in general much easier to learn, but since that the team is already used to Go, that wouldn't make much sense imho as it is a new ecosystem anyway. 


Erigon: 
* Go, from a purely economical perspective that alone is a strong argument for it, since the internal team already worked with Geth, and is used to Golang. 

* Way more stars, etc on GH, seems to be more mature (way more commits), also less open issues, etc. than Nethermind.


----

Bedrock requirements: 

* Erigon: 

Simply based on GH issues by searching for post-merge/PoS: Looks already very good even without looking for the specific API calls mentioned in the Bedrock docs. 
![Image](https://user-images.githubusercontent.com/28724551/178219457-ef0dd88e-56b9-4681-b77a-6aa01a7eb6fe.png)

And based on their docs, they support these API methods as well: 
https://github.com/ledgerwatch/erigon/blob/devel/cmd/rpcdaemon/README.md


![Image](https://user-images.githubusercontent.com/28724551/178220117-557c058a-d39c-4c35-8c58-273951c7e78b.png)



For me personally this would be a no-brainer, but I definitely don't have all the information, since I don't know our infrastructure that well as you all do. 


Happy for feedback, hope it helps.

**Comment by wsdt** [comment]
@InoMurko Could it make sense, to actually use the exact same Geth version Bedrock will be using to have a smooth as possible Bedrock migration and to migrate to another client after we successfully migrated to Bedrock? Or do you think, that this is fairly easy and comes without that many additional risks / potential delays?

Could be a (slightly) higher workload, but it could make things smoother, more stable, more secure and give us a faster time to market to not loose market share to Optimism or other Optimistic roll-ups at Bedrock launch. But yeah since client changes are close to non-existent seemingly, it could make sense to actually switch the client right away, happy for feedback!

**Comment by InoMurko** [comment]
As said, what would be useful is to see how we can compile erigon (or others) to mips: https://github.com/ethereum/go-ethereum/pull/23800/files

**Comment by wsdt** [comment]
**Erigon:**
Building go project with `GOARCH=mips` should work (for my understanding we just need to add it in their release `Makefile`. 
https://zchee.github.io/golang-wiki/GoMips/

Erigon itself has no documentation on that, but I requested Discord community access and opened a discussion on their GH. 

They currently don't provide any binaries in general, so we need to build it ourselves anyway. 
https://github.com/ledgerwatch/erigon/issues/4153

But I think compiling for Mips shouldn't be an issue (need to actually try this) since we are talking about a Go project here, and Go seems to support Mips out-of-the-box (plus that Geth built for Mips as well and just discontinued to do so, since xgo stopped supporting it). 

**Just asked in the Erigon Discord community: Got the confirmation that the Mips binary is even compiled automatically.** 

Happy for feedback.

**Comment by InoMurko** [comment]
> Just asked in the Erigon Discord community: Got the confirmation that the Mips binary is even compiled automatically.

Where is that being done?

**Comment by wsdt** [comment]
you mean the compilation?
![image](https://user-images.githubusercontent.com/28724551/179042429-370ba6f4-c015-4ec9-83d9-60043fa675ee.png)

**Comment by InoMurko** [comment]
Aha, because you mentioned automatically, I thought it's done somewhere in their CICD.

**Comment by wsdt** [comment]
No they don't have any official binaries: 
https://github.com/ledgerwatch/erigon/issues/4153

**Comment by InoMurko** [comment]
@wsdt can you fork Erigon, and make a circleci integration that compiles it to mips32?

**Comment by wsdt** [comment]
sure!

**Comment by wsdt** [comment]
@InoMurko just had a chat with Michael yesterday, he is also working on it. Just to keep you posted, that we both have a look at it.

**Comment by wsdt** [comment]
@mmontour1306 @InoMurko Just got the confirmation, that Erigon might NEVER support 32x architectures at all. 

The issues Michael and me encountered, seem to be bugs/issues with libraries they are using. Would mips64 also be an option @InoMurko ?

Raspberry works with Erigon, so according to them mips64 might/should work. Need to try today.

**Comment by wsdt** [comment]
@InoMurko `mips64` returns the exact same error messages for me, just asked in the Discord again. 

Another question, why don't we simply use their Docker image?

**Comment by InoMurko** [comment]
FYI: 
https://github.com/ethereum-optimism/minigeth/blob/c2b6152b4afb05e07514ad892304c117b2f72134/fetching-preimages.md

```
When run in prefetch mode, minigeth's role is to retrieve all the (hash -> preimage) mappings that are necessary to run the MIPS version of minigeth.
```

So the `minigeth` is a subset of `geth`:

As per cannon readme, minigeth is:
```
The pieces of geth needed to verify a block

See `../sync_minigeth.sh`, most of this is just geth and we can copy many of the files

The database has been abstracted in the `oracle/`, this does not use leveldb

Running on PC, it fetches all the required pieces of state from RPC.

Running on MIPS, it uses the oracle MMIO interface to get state based on hash.
```

So the question is - any idea which pieces prevent mips32?

**Comment by mmontour1306** [comment]
The Go language itself seems to have good support for a MIPS target, but it gets more difficult when you are trying to wrap a C library as is done with the cryptographic secp256k1 library. I have not been able to make that work while cross-compiling from my main desktop. I'm presently trying a native build of erigon inside my MIPS VM (last attempt ran out of disk space). It's slow and very memory-limited so I am not sure how far it will get.

64-bit might be an option, but the ultimate goal is to support a very stripped-down instruction set which can be implemented in an on-chain smart contract. That's probably easier with 32-bit registers.

**Comment by wsdt** [comment]
Really seems to be an issue also for both mips{32 and 64}
![image](https://user-images.githubusercontent.com/28724551/179267274-d339e66b-07fd-47f9-ae77-fb15d2aed8ed.png)

![image](https://user-images.githubusercontent.com/28724551/179267988-0978661c-2431-4c13-a393-aa8b55f9a1f6.png)


![image](https://user-images.githubusercontent.com/28724551/179267792-4cffe82b-1948-4bc9-b4e6-478d5151edaa.png)

**Comment by InoMurko** [comment]
> Really seems to be an issue also for both mips{32 and 64}
> 
> ![image](https://user-images.githubusercontent.com/28724551/179267274-d339e66b-07fd-47f9-ae77-fb15d2aed8ed.png)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/28724551/179267988-0978661c-2431-4c13-a393-aa8b55f9a1f6.png)
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/28724551/179267792-4cffe82b-1948-4bc9-b4e6-478d5151edaa.png)
> 
> 

Is Erigon2 a rewrite or the same repo? What are the changes?

**Comment by wsdt** [comment]
> > Really seems to be an issue also for both mips{32 and 64}
> > ![image](https://user-images.githubusercontent.com/28724551/179267274-d339e66b-07fd-47f9-ae77-fb15d2aed8ed.png)
> > ![image](https://user-images.githubusercontent.com/28724551/179267988-0978661c-2431-4c13-a393-aa8b55f9a1f6.png)
> > ![image](https://user-images.githubusercontent.com/28724551/179267792-4cffe82b-1948-4bc9-b4e6-478d5151edaa.png)
> 
> Is Erigon2 a rewrite or the same repo? What are the changes?

https://erigon.substack.com/p/erigon-2-three-upgrades?s=r

Found this :-)

**Comment by InoMurko** [comment]
Let's see where Erigon brings us.
