### ISSUE TITLE
Document contract changes needed for Bedrock specs

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#226]
Document know-how for Bedrock level changes (comparing it to the current system) and leave them here.

Contract relevant: https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock

The point of this issue is to provide know-how for the rest of the team.
Output should be resources and an understanding what the purpose of L1 and L2 contract is, how they fit in the grand schema of the system overall.

**Comment by wsdt** [comment]
https://github.com/ethereum-optimism/optimism/blob/develop/specs/overview.md

**Comment by wsdt** [comment]
As we all already know, Bedrock is not just an "update" is a completely new architecture. I will try to best summarize some insights I have gained, link some interesting resources I've found as well as try to point out specific differences if possible. 

### Spotted code/structural changes in particular

Despite using a new project structure and therefore new composition of contracts, contracts that seem to be the equivalent to the current system (e.g. `L1CrossDomainMessenger.sol`) **try to sustain the same interface which is great**. In the case of the crossDomainMessenger for example, they have the same method signatures in majority, despite using different parent contracts (inheritance). In general more usage of inheritance. 

Still having some [minor legacy contracts](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock/contracts/legacy) (seem to be completely identical to the current system, except of minor refactoring).

They use the quite new `reinitializer` of OpenZeppelin to upgrade & version their contracts and have a convention to have the contract version as `constant` on top of each contract. 

They test their contracts partly via Foundry/Forge as well as hardhat (ts) as usual [Some Solidity tests](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock/contracts/test). Looks like they might be switching to Foundry mid-term. 

In general it seems like they massively simplified their contract architecture. Looks like they have way less contracts in general. 

Libraries in `/rlp`, `/trie` and those in the legacy folder seem to be identical to the current system. In general identical-named libraries to seem to be identical to a large extent (e.g. `Lib_CrossDomainUtils`). 

**Most contracts such as L2CrossDomainMessenger, L2StandardBridge, ..**: 
- Now upgradable
- Otherwise very similar besides using proxies & inheritance to abstract
- In general many interfaces disappeared or are inlined
- Better inline-documentation

### Contracts purpose/architecture
[Here](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts/docs) is a list of markdown documentations of the current contract structure. I'll try to outline some key-differences below in conjunction with comparing the [current system contracts](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts/contracts) and the new [bedrock contracts](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock/contracts).

#### L1 - Contract Overview (almost all of them are to be deployed behind proxies): 
- ´L1CrossDomainMessenger` still exists
- `L1StandardBridge` still exists
- `L2OutboundOracle` (**new**): L2 state committed to this contract
- `OptimismPortal` (**new**): Low level contract for passing messages between L1 and L2. No replayability, users should use `L1CrossDomainMessenger` instead. 
- ResourceMetering (**new**): Pricing updates automatically based on current demand ([EIP-1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md))
- `AddressDictator` **seems to be removed** [here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/L1/deployment/AddressDictator.sol)
- `ChugSplashDictator` still part of the [legacy](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/legacy/L1ChugSplashProxy.sol) contracts
- The whole `L1/rollup/` folder with all its contracts seems to be [gone](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts/contracts/L1/rollup) (probably replaced by `L2OutboundOracle`).
- `TeleportrDeposit` **seems to be removed** [here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/L1/teleportr/TeleportrDeposit.sol)
- `Bondmanager` **seems to be removed** [here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/L1/verification/BondManager.sol)

#### L2 - Contract Overview (almost all of them are to be deployed behind proxies): 
- `L2CrossDomainMessenger` still exists
- `L2StandardBridge` still exists
- `L2StandardTokenFactory` [here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/L2/messaging/L2StandardTokenFactory.sol) moved and renamed to `OptimismMintableTokenFactory` [here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/universal/OptimismMintableTokenFactory.sol)
- `OVM_DeployerWhitelist`, `OVM_L2ToL2MessagePasser`, `OVM_GasPriceOracle`, `OVM_SequencerFeeVault`, `iOVM_L1BlockNumber` renamed to same name without `(i)OVM_` prefix (L1BlockNumber now a contract)
- `WETH9`, `OVM_ETH` still exist
- `TeleportrDisburser` **seemingly removed** [here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/contracts/L2/teleportr/TeleportrDisburser.sol)

#### Universal
Some parent contracts that are used across the infrastructure, [here](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock/contracts/universal). 


Will further add more insights I gain throughout the week, but I think that gives first insights into the new bedrock contract architecture. Happy for feedback! Thank you.

**Comment by wsdt** [comment]
### Withdrawals:
- Since that we discontinued funding the fast exit back to L1, this could now become cheaper: 

"[Address aliasing](https://community.optimism.io/docs/developers/build/differences/#address-aliasing) is now applied to withdrawal transactions as well as deposit ones.

There is a separate withdrawal root which allows withdrawal merkle proofs to be 60% cheaper (in L1 gas). This happens transparently, you just see less cost."

Source: https://community.optimism.io/docs/developers/bedrock/#deposits-from-ethereum-to-optimism

### Further internal changes:
- No longer a CTC contract. L2 blocks are now directly saved to L1 by using a non-contract address `0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0001` to minimize L1 gas expense.
- In Bedrock ETH is treated exactly as it is in Ethereum. Previously ETH was stored in a system level contract at `0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000`. 

Source: https://community.optimism.io/docs/developers/bedrock/#legacy-requests

**Comment by wsdt** [comment]
guess this is obsolete as stale
