### ISSUE TITLE
Figure out how Boba v3 can live side-by-side to Boba V2

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#255]
Project structure that best suites us?
Requirements:
- Current Boba version needs to live side by side with future Boba version
  - contracts from Optimism, and slowly introducing services (the first one being the execution engine (aka l2geth but not really geth)
- Future Boba version needs to be tested in CirleCI (our preferred tool going forwards)
- the intial client implementation would need to be tested against Optimisms stack (as we have more core changes (dual fees, turing,...)
- ... any other. you think of? Place them here.
- Figure out the final way of state migration between v2 and v3 (could be the same way bedrock is applied)

**Comment by wsdt** [comment]
### General project structure

Assuming Boba v3 will replace v2 at some point, separating it via two major branches might be best imho, sounds too simple but actually that feels like exactly the use-case of having branches. 

Assuming both Boba v3 and Boba v2 will be live at the same time then, then we could also think about just having two separate repositories, since the architecture is very different. To make maintainability slightly easier, we could think about outsourcing identical files (if we are sure they always be the same for both, at least for a long time) to a separate submodule if we want to update v2 as well. But yes, this can also introduce unnecessary complexity: **Make it as easy as it can be but not simpler.** 

As far as I remember/know, Optimism uses approach 2 by just having two separate repos. 

Or what are your thoughts about this? 

### Test client implementation
Since we have several core changes, and assuming we want to be up-to-date with their repository (or rather releases probably), we could refer a link/badge to their tests + running the tests on our stack as well (including our own for sure). Just want to keep things simple, or what were your thoughts? 


What do you mean with the last point? Actually upgrading to v3 on testnet then?

**Comment by InoMurko** [comment]
Here are some of the requirements I can think of:

In fact, we will never have two systems LIVE in production at the same time. Bedrock is an upgrade rather than a new version of the system. What we do need is to be able to have developers run two flavours of the system locally.

Some of the services will have overlap and will live in both systems, like gas-price-oracle,gateway,subgraph.
Bedrock is basically this: https://github.com/ethereum-optimism/optimism/blob/32c82ea95f0627bf473dadefcba296fd608fd26a/ops-bedrock/docker-compose.yml
https://github.com/ethereum-optimism/optimism/blob/32c82ea95f0627bf473dadefcba296fd608fd26a/ops-bedrock/devnet-up.sh

> As far as I remember/know, Optimism uses approach 2 by just having two separate repos.

They started this way. But now they're back at the monorepo, everything in develop/master approach.

> What do you mean with the last point? Actually upgrading to v3 on testnet then?

The block production is a little bit different now and how it will be after Bedrock (regardless of Erigon). So we don't exactly know how the sync between current production l2geth and Bedrock Erigon will look like.

I don't think there's a better approach than what we can observe upstream.
One thing I don't like is having everything on root dir. I would place bedrock specific services like op-batcher, op-node into a /bedrock/ folder.

@wsdt should we add Erigon to boba/bedrock/erigon as a git submodule? http://www.devops-blog.net/git/updating-a-git-submodule-from-a-forked-repo-on-github
fyi, the idea is to keep Erigon as up-to-date as possible and sync often from upstream, while applying Rollup changes
We should also add https://github.com/ethereum-optimism/reference-optimistic-geth because we need to have Bedrock work with both clients as block producers.

**Comment by mmontour1306** [comment]
Erigon expects to be in its own git repo and the Makefile includes code to update its own submodules at the start of a build. We would need to make some changes there to have it work as a submodule or subtree inside our repo.

**Comment by wsdt** [comment]
> 



> Erigon expects to be in its own git repo and the Makefile includes code to update its own submodules at the start of a build. We would need to make some changes there to have it work as a submodule or subtree inside our repo.

Why shouldn't it work? 
`git submodule update --init --recursive`

`If --recursive is specified, this command will recurse into nested submodules, and show their status as well.`

https://git-scm.com/docs/git-submodule

**Comment by wsdt** [comment]
The sync should work with #281
