### ISSUE TITLE
[ETHBogota Workshop] in-person workshop

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#378]
[ ] intro to rollups + the future of boba (erigon and fraud proving) - SLIDES
[ ] what is Hybrid Compute - SLIDES

Hybrid Compute usage
[ ]  How can hybrid compute be used - EXAMPLE

[ ]   (story from The Andromeda University NFTs + EvoVerses use case)
[ ]  A Github project that points to Rinkeby Boba with self contained examples.
```
Import XXX contract
Adding XXX function in your contract
Adding credits to your turingHelper
```
This helps developers know what exactly they should do so that they're able to use Hybrid Compute.
`make test`
Deploys contracts to Rinkeby Boba, executes tests in the folder

Work on https://docs.boba.network/turing (rename to hybrid-compute)
[ ]  Hybrid compute docs docs (how to add code to your code (link the GH project above))
[ ]  Token and contract addresses needed
[ ]  Gas fee (make clear that we move l1SecurityFee to gas usage)
Specifically the changes for L2s on alt L1s (Turing credit)

**Comment by wsdt** [comment]
@mmontour1306 Can the extended payload HybridCompute version already be publicly used? 

---

1. Do we have the slides already? Would assume so? Would I also be presenting rollups & HC from the theoretic POV?
2. Sure can show how to use HybridCompute in a workshop! Haven't been involved in EvoVerses yet, would be great if you could give me some insights here. 
3. I think it would make sense to have a repository with in one folder the start project (so that people don't have setup difficulties during the workshop, except it's not hands-on and just a presentation) + the final result in another folder. 

@InoMurko

**Comment by InoMurko** [comment]
1,2 will give you updates here!

**Comment by mmontour1306** [comment]
https://github.com/bobanetwork/boba/pull/204 needs to be reviewed and merged into the develop branch. I've removed the "don't merge yet" label. The previous test failures were evidently intermittent or unrelated to my code changes since I did get one clean run prior to the most recent merge from develop (which is still running its tests).

**Comment by InoMurko** [comment]
> 1,2 will give you updates here!

2.:
https://github.com/EvoVerses/contracts/blob/main/contracts/npc/BreederBetty/BreederBetty.sol
https://thedefiant.io/boba-launches-on-avalanche

**Comment by wsdt** [comment]
Repository for the workshop: 
https://github.com/bobanetwork/HybridCompute_Tutorial

Will do a starter and finish branch. 

---

After discussing with Ino, I'll move away from the local setup and document for the public testnet with a preconfigured public endpoint that is deployed by us.

**Comment by wsdt** [comment]
Updated the documentation of the workshop: 
https://github.com/bobanetwork/HybridCompute_Tutorial

https://github.com/bobanetwork/HybridCompute_Tutorial/blob/non-local/README.md

Feedback welcome
