### ISSUE TITLE
[AA] optimization: paymasterAndData for aa-sdk and simulateUserOp on bundler

### ISSUE THREAD

**Issue by souradeep-das** [bobanetwork/boba_legacy#689]
## Expected Behaviour
- use paymasterAPI on the sdk to build userOperations involving paymaster directly
- alternatives for simulateUserOp on bundler (dependent on new bundler)

## Current Behaviour
- paymasterAndData is explicitly added in when creating an userOp
- bundler does not simulate user op

**Comment by InoMurko** [comment]
is this sorted?

**Comment by souradeep-das** [comment]
the second part of the issue: "bundler does not simulate user op" should be fixed with the simulation through the wrapper you added.

the first part: "paymasterAndData is explicitly added in when creating an userOp" we will have to check if this is still an issue even after applying the new bundler_sdk

**Comment by wsdt** [comment]
yes, if you look at the tests here https://github.com/bobanetwork/boba/blob/develop/integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts#L200 we are overriding and adding the 'paymasterAndData' field on the userOp
while the best way should be using the paymasterAPI field from simpleAccountAPI, and with that whenever the sdk would be used to generate a userOp it would include the paymasterAndData field - but that fails for some reason. essentially adding the paymasterAPI on the simpleAcccountAPI fails


this issue is still there with the new bundler_sdk, i think if we follow the paymasterAPI field and the userOp creation on the sdk(when the paymaster field exists) - we could get closer to the solution or the reason

**Comment by wsdt** [comment]
I guess here we got already the explanation for the issue, will dig deeper: 

```ts 
/**
   * @param userOp a partially-filled UserOperation (without signature and paymasterAndData
   *  note that the "preVerificationGas" is incomplete: it can't account for the
   *  paymasterAndData value, which will only be returned by this method..
   * @returns the value to put into the PaymasterAndData, undefined to leave it empty
   */
  async getPaymasterAndData (userOp: Partial<UserOperationStruct>): Promise<string | undefined> {
    return '0x'
  }
```
